name: Deploy

on:
  release:
    types: [created]

jobs:
  deploydoc:
    name: Deploy document
    runs-on: ubuntu-latest
    env:
      PREFIX: /usr 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
    - name: Install dependencies
      run: |
        sudo git clone https://github.com/pylover/python-makelib.git /usr/local/lib/python-makelib
        make install-common install-doc editable-install
    - name: Sphinx Build
      working-directory: sphinx
      run: |
        make html
        touch _build/html/.nojekyll 
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        BRANCH: gh-pages
        FOLDER: sphinx/_build/html
        CLEAN: true

  deploypypi:
    name: Deploy to PyPI
    needs: deploydoc
    runs-on: ubuntu-latest
    env:
      PREFIX: /usr 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
    - name: Install dependencies
      run: |
        sudo git clone https://github.com/pylover/python-makelib.git /usr/local/lib/python-makelib
        make install-common editable-install
    - name: Create distributions
      run: make sdist wheel
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
