name: Sphinx

on:
  push:
    tags:
      - 'v*'

jobs:
  sphinx:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-ci.txt
        python -m pip install -e .
    - name: Sphinx Build
      working-directory: sphinx
      run: |
        make html
        touch _build/html/.nojekyll 
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: sphinx/_build/html # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from deploy branch
